apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: diskCapacity
            operator: In
            values:
            - low
            - medium
  containers:
  - name: nginx-container
    image: nginx